# Generated by Django 5.2.1 on 2025-05-24 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('bank_slip', 'Boleto')], max_length=20)),
                ('payment_status', models.CharField(choices=[('waiting_payment', 'Aguardando Pagamento'), ('paid', 'Pago'), ('authorized', 'Autorizado'), ('refused', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], max_length=20)),
                ('amount', models.IntegerField(help_text='Valor em centavos')),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_created_at', models.DateTimeField(blank=True, null=True)),
                ('payment_updated_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('sms_scheduled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-webhook_received_at'],
                'indexes': [models.Index(fields=['payment_method', 'payment_status'], name='webhooks_we_payment_546774_idx'), models.Index(fields=['webhook_received_at'], name='webhooks_we_webhook_3f285e_idx'), models.Index(fields=['processed'], name='webhooks_we_process_cbb47e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('twilio_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou'), ('delivered', 'Entregue'), ('undelivered', 'Não Entregue')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_unit', models.CharField(blank=True, max_length=5, null=True)),
                ('webhook_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='webhooks.webhookevent')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['status'], name='webhooks_sm_status_8e6eac_idx'), models.Index(fields=['sent_at'], name='webhooks_sm_sent_at_88ccdb_idx')],
            },
        ),
    ]
