# Generated by Django 5.0.7 on 2025-05-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='duplicate_reason',
            field=models.TextField(blank=True, help_text='Motivo pelo qual foi considerado duplicata', null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='is_duplicate_attempt',
            field=models.BooleanField(default=False, help_text='Indica se foi uma tentativa de envio duplicado'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='related_webhook_ids',
            field=models.JSONField(blank=True, help_text='IDs de webhooks relacionados/similares', null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='duplicate_key',
            field=models.CharField(db_index=True, default=1, help_text='Chave única para detectar duplicatas por telefone+valor+método', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='last_sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='Último horário de envio de SMS', null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='sms_sent_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de SMS enviados para este webhook'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou'), ('delivered', 'Entregue'), ('undelivered', 'Não Entregue'), ('blocked_duplicate', 'Bloqueado - Duplicata')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['phone_number', 'sent_at'], name='webhooks_sm_phone_n_e39e14_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['is_duplicate_attempt'], name='webhooks_sm_is_dupl_5588da_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['customer_phone', 'payment_method', 'amount'], name='webhooks_we_custome_60d589_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['duplicate_key'], name='webhooks_we_duplica_24afa1_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['sms_scheduled', 'payment_method', 'payment_status'], name='webhooks_we_sms_sch_e90568_idx'),
        ),
    ]
