# Generated by Django 5.0.7 on 2025-05-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_smslog_duplicate_reason_smslog_is_duplicate_attempt_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_payment_5ac704_idx',
            old_name='webhooks_we_payment_546774_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_webhook_b258e6_idx',
            old_name='webhooks_we_webhook_3f285e_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_process_59a124_idx',
            old_name='webhooks_we_process_cbb47e_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_custome_3a02a8_idx',
            old_name='webhooks_we_custome_60d589_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_duplica_20e243_idx',
            old_name='webhooks_we_duplica_24afa1_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_sms_sch_c0c1d3_idx',
            old_name='webhooks_we_sms_sch_e90568_idx',
        ),
        migrations.AlterModelTable(
            name='webhookevent',
            table='webhook_events',
        ),
    ]
