# Generated by Django 5.0.7 on 2025-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_rename_webhook_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='pending_task_ids',
            field=models.JSONField(blank=True, help_text='Lista de task IDs do Celery pendentes para este webhook', null=True),
        ),
    ]
