version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://sms_user:sms_password@db:5432/sms_sender_db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sms_sender_db
      - POSTGRES_USER=sms_user
      - POSTGRES_PASSWORD=sms_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A sms_sender worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://sms_user:sms_password@db:5432/sms_sender_db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A sms_sender beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://sms_user:sms_password@db:5432/sms_sender_db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env

volumes:
  postgres_data:
