version: "0.1"
build:
  commands:
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
    - python manage.py migrate

services:
  - type: web
    name: sms-sender-web
    env: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "./start_render.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "sms_sender.settings"
      - key: WEB_CONCURRENCY
        value: 3
      - key: SERVICE_TYPE
        value: "web"

  - type: worker
    name: sms-sender-worker
    env: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "./start_render.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: "sms_sender.settings"
      - key: C_FORCE_ROOT
        value: true
      - key: CELERY_TASK_ALWAYS_EAGER
        value: false
      - key: SERVICE_TYPE
        value: "worker"

  - type: worker
    name: sms-sender-beat
    env: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "./start_render.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: "sms_sender.settings"
      - key: C_FORCE_ROOT
        value: true
      - key: SERVICE_TYPE
        value: "beat"

databases:
  - name: sms-sender-db
    plan: starter

redis:
  - name: sms-sender-redis
    plan: starter
